---
# chocomilk vars

# Package Changelog
changelog: "https://release-monitoring.org/api/v2/versions/?project_id=325924"
changelog_format: json

# Get Version
version: "5.2.0.1"

# Download URL
url: "https://www.archimatetool.com/downloads/archi_5.php?/5.2.0/Archi-Win64-Setup-5.2.0.exe"

searchreplace:
  "tools/chocolateyinstall.ps1":
    - regwxp: (^\s*[$]*urlPackage\s*=\s*)('.*')
      replace: "$urlPackage = '{{ url }}'"
    - regwxp: (^\s*[$]*checksumPackage\s*=\s*)('.*')
      replace: "$checksumPackage = '{{ file_hash }}'"
    - regwxp: (^\s*[$]*urlPackage64\s*=\s*)('.*')
      replace: "$urlPackage64 = '{{ url }}'"
    - regwxp: (^\s*[$]*checksumPackage64\s*=\s*)('.*')
      replace: "$checksumPackage64 = '{{ file_hash }}'"

# readme to description
readme:
  start: 6
  end: 16

# deploy
deploy:
  - provider: chocolatey
    repository: "https://push.chocolatey.org/"
    key: "{{ lookup('env','CHOCOLATEY_ORG_API_KEY') }}"
  - provider: chocolatey
    repository: "https://nuget.itigo.tech/upload"
    key: "{{ lookup('env','CHOCOLATEY_ITIGO_API_KEY') }}"
  - provider: github
    name: "OpenCircle-Choco-Bot"
    email: "chocomilk@open-circle.ch"
    url: github.com/open-circle-ltd/chocolatey.archi.git
    key: "{{ lookup('env','GITHUB_API_KEY') }}"

# Notification
notifications:
  - provider: mattermost
    url: 'https://chat.open-circle.ch'
    key: "{{ lookup('env','MATTERMOST_API_KEY') }}"
    channel: 'notification-chocolatey'
